apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness-probe-task-deployment
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      task: liveness-probe
  template:
    metadata:
      labels:
        task: liveness-probe
    spec:
      containers:
        - name: nginx-app
          image: nginx:stable
          ports:
            - containerPort: 80