apiVersion: batch/v1
kind: CronJob
metadata:
  name: date-cron-job
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: date
              image: busybox
              command:
                - /bin/sh
                - -c
                - date
          restartPolicy: OnFailure
  schedule: "*/5 * * * *" 


