replicaCount: 3

image:
  repository: konbusalov/secret-phrase-image
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "alb"
  annotations: 
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
    - host: antonkon.ddns.net
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: clusterip
              port:
                number: 8080

env: 
  - name: SECRET 
    valueFrom:
      secretKeyRef:
        name: db-secrets-manager
        key: DB_PASSWORD
