apiVersion: external-secrets.io/v1
kind: ExternalSecret 
metadata:
  name: test-external-secret
  namespace: default
spec:
  refreshInterval: '0'
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: db-secrets-manager
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: ingress-task-test-secret 
        property: db-password
