apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx 
  labels:
    app: nginx
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-app
          image: nginx
          ports:
            - containerPort: 8000