apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-1
  namespace: app1
  annotations:
    creator_email: konstantin.busalov@innowise.com
  labels:
    app: app1
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-2
  namespace: app2
  annotations:
    creator_email: konstantin.busalov@innowise.com
  labels:
    app: app2
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
