apiVersion: v1
kind: Service
metadata:
  name: service-task-clusterip-service
spec:
  selector:
    task: services
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP 
  type: ClusterIP
--- 
apiVersion: v1
kind: Service
metadata:
  name: service-task-nodeport-service
spec:
  selector:
    task: services
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP 
  type: NodePort
