apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default 
  source:
    repoURL: 'https://github.com/konbusalov/ArgoCD_Task_Helm_Repo.git'
    targetRevision: main
    path: argocd-task-chart/
    helm:
      parameters:
        - name: "service.port"
          value: "8080"
      valueFiles:
        - values-dev.yaml
      values: |
        # replicaCount:2
        serviceAccount:
          create: true
          annotations:
            demo/role: demo-annotation
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kuber
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true