replicaCount: 6

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.29.2"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "alb"
  annotations: 
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
    - host: konstantinbusalov.ddns.net
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: clusterip
              port:
                number: 8080